[package]
name = "raft"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
config = "0.14.0"
dotenv = "0.15.0"
serde = "1.0.203"
serde_json = "1.0.120"
tokio = "1.38.0"
